---
title: "Reading Data from the Web"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

library(rvest)
library(httr)

knitr::opts_chunk$set(
  	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
```


# Scrape a Table


Get first table from this page (http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)


## read in the html

```{r}
drug_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(drug_url) 

drug_use_html
```


## extract the table; focus on the first one

```{r}
tbl_maj = 
   drug_use_html %>% 
  html_nodes(css = "table") %>% 
  first() %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```


# Use CSS Selector


## star war info

data from "https://www.imdb.com/list/ls070150896/"

```{r}
sw_url = "https://www.imdb.com/list/ls070150896/"

sw_html = read_html(sw_url)

sw_html
```

get elements using CSS Selector (from web page), build data

```{r}
title_vec = 
  sw_html %>% 
  html_nodes(css = ".lister-item-header a") %>% 
  html_text()

gross_rev_vec = 
  sw_html %>% 
  html_nodes(css = ".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()

runtime_vec = 
  sw_html %>% 
  html_nodes(css = ".runtime") %>% 
  html_text()

sw_df = 
  tibble(
    title = title_vec,
    gross_rev = gross_rev_vec,
    runtime = runtime_vec
  )
```


# Working with API


## get NYC water data

```{r}
NYCwater_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")

water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble( )
```


## BRFSS data

```{r}
brfss_2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

